name: CI

on:
  workflow_dispatch: { }

  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  CI:
    name: CI

    runs-on: [ coveo, linux, x64, eks memory-request=6G memory-limit=8G ]

    steps:
      - name: test
        run: echo "tester face"
